#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset
gcc -DHAVE_CONFIG_H -I.    -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=missing-include-dirs -Werror=aggregate-return -g -O2 -c -o bwrap-bubblewrap.o `test -f './bubblewrap.c' || echo './'`./bubblewrap.c
gcc -DHAVE_CONFIG_H -I.    -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=missing-include-dirs -Werror=aggregate-return -g -O2 -c -o bwrap-bind-mount.o `test -f './bind-mount.c' || echo './'`./bind-mount.c
gcc -DHAVE_CONFIG_H -I.    -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=missing-include-dirs -Werror=aggregate-return -g -O2 -c -o bwrap-network.o `test -f './network.c' || echo './'`./network.c
gcc -DHAVE_CONFIG_H -I.    -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=missing-include-dirs -Werror=aggregate-return -g -O2 -c -o bwrap-utils.o `test -f './utils.c' || echo './'`./utils.c
gcc -pipe -Wall -Werror=empty-body -Werror=strict-prototypes -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=format=2 -Werror=format-security -Werror=format-nonliteral -Werror=pointer-arith -Werror=init-self -Werror=missing-declarations -Werror=return-type -Werror=overflow -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=missing-include-dirs -Werror=aggregate-return -g -O2   -o bwrap bwrap-bubblewrap.o bwrap-bind-mount.o bwrap-network.o bwrap-utils.o
